name: Hasura CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hasura CI/CD
        #uses: GavinRay97/hasura-ci-cd-action@v1.1
        uses: ./.github/actions/hasura-ci-cd
        with:
          PATH_TO_HASURA_PROJECT_ROOT: ./hasura
          HASURA_CLI_VERSION: v2.0.0-alpha.3
          HASURA_ENDPOINT: https://ci-cd-demo-1.hasura.app
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          # If you want to disable either migrations or regression tests, make sure to remove them completely
          # The script only checks for their presence, not their value
          HASURA_MIGRATIONS_ENABLED: true
